"""empty message

Revision ID: 447e54c62b9b
Revises: 9c702d850eb8
Create Date: 2022-03-02 14:33:37.118270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447e54c62b9b'
down_revision = '9c702d850eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
